"""create favorites tables

Revision ID: cb202d3157f1
Revises: 7acd97c5df1b
Create Date: 2025-04-29 10:44:57.896305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb202d3157f1'
down_revision: Union[str, None] = '7acd97c5df1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_patterns',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('pattern_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('username', 'pattern_id')
    )
    op.create_table('favorite_yarns',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('yarn_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('username', 'yarn_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_yarns')
    op.drop_table('favorite_patterns')
    # ### end Alembic commands ###
